version: '2.4'

services:
  portfolio:
    build: 
      context: .
      target: dev
    init: true
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next